### PR TITLE
Update/balance img

### PR DESCRIPTION
**Pull request by shreyaansjain06**
#### Description of the change
Balance the image

#### Screenshots
Screenshot 2021-10-15 at 3 57 14 PM

#### Checklist

- [x] Added description of the change
- [x] I've read the [contributing guidelines](https://github.com/web3community/devprotocol.xyz/blob/master/CONTRIBUTING.md)
- [x] Search previous suggestions before making a new PR, as yours may be a duplicate.
- [x] I acknowledge that all my contributions will be made under the project's license.

Notes (**optional**):

### CODE REVIEW

**Review by gptkrsh — CHANGES_REQUESTED** [review]
Remove the changelog changes

**Review by vinzvinci — CHANGES_REQUESTED** [review]
the image become smaller, please follow the design here 👇 

https://devprotocol.xyz/

**Comment by krishguptadev** [comment]
> > > the image become smaller, please follow the design here 👇
> > > https://devprotocol.xyz/
> > 
> > 
> > so you want the third image to be greater than all?
> 
> no greater, make it all balance and the size should look like 👇 image
> 
> 
> don't change the alignment of "Latest on Medium"

Vincent, I think what you are saying is not possible, either the image would be stretched or smaller. The only way to fix this without complications is to directly made the images of the same aspect ratio on medium

**Comment by vinzvinci** [comment]
> > > > the image become smaller, please follow the design here 👇
> > > > https://devprotocol.xyz/
> > > 
> > > 
> > > so you want the third image to be greater than all?
> > 
> > 
> > no greater, make it all balance and the size should look like 👇 image
> > don't change the alignment of "Latest on Medium"
> 
> I mean like in this the third image height is larger than all you wan something like this

there's no problem with that, we are using API, it comes from medium

**Comment by shreyaansjain06** [comment]
Do you have any idea why these extra things are coming in pr i have not committed them or changed them

**Comment by vinzvinci** [comment]
> > > > the image become smaller, please follow the design here 👇
> > > > https://devprotocol.xyz/
> > > 
> > > 
> > > so you want the third image to be greater than all?
> > 
> > 
> > no greater, make it all balance and the size should look like 👇 image
> > don't change the alignment of "Latest on Medium"
> 
> Vincent, I think what you are saying is not possible, either the image would be stretched or smaller. The only way to fix this without complications is to directly made the images of the same aspect ratio on medium

Ah didn't see krish message, yes this is from medium image I think, I think this PR should not continue?

**Comment by vinzvinci** [comment]
Thanks for your contributions @shreyaansjain06, really appreciate your work. Please see other bugs to our projects :D sorry for confusion.

Thanks for bringing up that @krishguptadev, I will tell them.

**Pull request closed without merging**
