### PR TITLE
Feature: Replace DEVToken

### LINKED ISSUE #110: [FEATURE] Replace the design in DEV Token section
### Current
ss
### Wanted
Wanted

### Context

You can see the design here - https://www.figma.com/file/rmCKKIsjSWCH0q6lObDQC8/Dev-Protocol-design?node-id=0%3A1

### Possible implementation

_No response_

### Additional information

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by AbhinavMV**
#### Description of the change
Replaced the DEV token section as mentioned in issue.

Closes #110 
#### Screenshots

image
image

#### Checklist

- [x] Added description of the change
- [x] I've read the [contributing guidelines](https://github.com/web3community/devprotocol.xyz/blob/main/CONTRIBUTING.md)
- [x] Search previous suggestions before making a new PR, as yours may be a duplicate.
- [x] I acknowledge that all my contributions will be made under the project's license.

Notes (**optional**): 

<a href="https://gitpod.io/#https://github.com/web3community/devprotocol.xyz/pull/140"></a>

### CODE REVIEW

**Review by vinzvinci — APPROVED** [review]

**Review by shuklaritvik06 — APPROVED** [review]
LGTM

**Review by Pradumnasaraf — APPROVED** [review]
LGTM

**Comment by vinzvinci** [comment]
Thanks for your contributions! 

Can u also do this #134?

**Review by gptkrsh — COMMENTED** [review]
LGTM!

**Review by Panquesito7 — COMMENTED** [review]
LGTM! 🚀

**Pull request merged**
