### PR TITLE
Fixed toggle switch for navbar

### PR DESCRIPTION
**Pull request by ZaidKhan2002**
#### Description of the change

Fixed Toggle switch for tablet size.

#84 

#### Screenshots
Screenshot 2021-10-27 at 5 55 05 PM

Screenshot 2021-10-27 at 6 00 44 PM

#### Checklist

- [x] Added description of the change
- [x] I've read the [contributing guidelines](https://github.com/web3community/devprotocol.xyz/blob/master/CONTRIBUTING.md)
- [x] Search previous suggestions before making a new PR, as yours may be a duplicate.
- [x] I acknowledge that all my contributions will be made under the project's license.

Notes (**optional**): 

<a href="https://gitpod.io/#https://github.com/web3community/devprotocol.xyz/pull/85"></a>

### CODE REVIEW

**Review by gptkrsh — CHANGES_REQUESTED** [review]
Please do not commit package files

**Review by gptkrsh — CHANGES_REQUESTED** [review]

**Review by gptkrsh — APPROVED** [review]
nvm, I think merging the package lock file won't make a big difference

**Review by shuklaritvik06 — APPROVED** [review]
LGTM :)

**Review by Panquesito7 — COMMENTED** [review]
LGTM! 🚀

**Review by mkubdev — COMMENTED** [review]
Noice @krishguptadev 🛩️

**Pull request merged**
