### PR TITLE
fix: vertical alignment

### LINKED ISSUE #124: [BUG] 3 pages different placement
### Problem subject

I would like the text and images to appear in the same place on all three screens of `for Creators`, `for Patrons`, & `for Developers`.

### Description

image

### Expected behavior/contents

The placement should not different

### Actual behavior/contents

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### LINKED ISSUE #143: [FEATURE] Set the navbar position fixed
### Problem subject

Navbar

### Description

Navbar is not sticky at top in any of the pages.

### Expected behavior/contents

Navbar should be sticky so that user can navigate using Navbar rather then scrolling up.

### Actual behavior/contents

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### LINKED ISSUE #144: [FEATURE] Set the navbar position fixed
### Detailed description

I want this navbar position fixed when the user scroll
image

### Context

It is better, so they can still visit the links in navbar when they scroll 

### Possible implementation

_No response_

### Additional information

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by gptkrsh**
fixes #143 

fixes #144 

fixes #124 

<a href="https://gitpod.io/#https://github.com/web3community/devprotocol.xyz/pull/146"></a>

### CODE REVIEW

**Review by vinzvinci — COMMENTED** [review]
I like the changes in 3 pages (creators, patrons, developers)

On the home page, this thing moves upward 
image

I like the current one
image

What do u think?

**Comment by krishguptadev** [comment]
> I like the changes in 3 pages (creators, patrons, developers)
> 
> On the home page, this thing moves upward image
> 
> I like the current one image
> 
> What do u think?

But I didn't edit the home page 🤔 Anyways, will fix this

**Review by vinzvinci — CHANGES_REQUESTED** [review]
Sorry, but I don't know why it look like this

The latest you commit is still different, when you look on mobile view, it has extra white space. On my screen, the desktop view also got so much whitespace, the current one looks good.

Please compare https://deploy-preview-146--devprotocol.netlify.app/ 👉 https://devprotocol.netlify.app/

The users like the current homepage and we should keep it at is.

**Comment by shuklaritvik06** [comment]
> Sorry, but I don't know why it look like this
> 
> The latest you commit is still different, when you look on mobile view, it has extra white space. On my screen, the desktop view also got so much whitespace, the current one looks good.
> 
> Please compare https://deploy-preview-146--devprotocol.netlify.app/ point_right https://devprotocol.netlify.app/
> 
> The users like the current homepage and we should keep it at is.

Yep now there is so many whitespace

**Review by vinzvinci — CHANGES_REQUESTED** [review]
Could u also check, when I scroll in these pages (creators, patrons). I can't click the navbar items in step by step section 🤔 maybe this is another issue to create and new PR?

**Comment by mkubdev** [comment]
> Could u also check, when I scroll in these pages (creators, patrons). I can't click the navbar items in step by step section 🤔 maybe this is another issue to create and new PR?

Me too! Margin aren't the same everywhere too.

**Comment by shuklaritvik06** [comment]
Same for me too

**Comment by krishguptadev** [comment]
> Could u also check, when I scroll in these pages (creators, patrons). I can't click the navbar items in step by step section 🤔 maybe this is another issue to create and new PR?

That bug was not there for me 🤔 But still added a fixture... (I think which will fix this)

**Review by vinzvinci — APPROVED** [review]
LGTM 👍 Thank you so much Krish 🎉

**Review by Panquesito7 — APPROVED** [review]
Awesome! 🚀 Thank you! 😄👍

**Pull request merged**
