### PR TITLE
Fix Dark Mode

### LINKED ISSUE #87: [FEATURE] Add a dark mode to the website
### Detailed description

I think a dark mode should be added to the website. I currently use Dark Reader to make the websites dark, but for Dev Protocol, it doesn't look that good, IMO.

image

### Context

Many users do not like the light mode, they prefer dark mode (like me 😂), so I think it'd be a good idea to add a dark mode to the website.

### Possible implementation

Add a dark mode to the website, that can be toggled with a button in the navbar.

### Additional information

Nope.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by AbhinavMV**
#### Description of the change

close #87 

#### Checklist

**I agree to the following :-**

*   Added description of the change
*   I've read the [contributing guidelines](https://github.com/web3community/devprotocol.xyz/blob/main/CONTRIBUTING.md)
*   Search previous suggestions before making a new PR, as yours may be a duplicate.
*   I acknowledge that all my contributions will be made under the project's license.

Notes (**optional**): 

<a href="https://gitpod.io/#https://github.com/web3community/devprotocol.xyz/pull/147"></a>

### CODE REVIEW

**Comment by AbhinavMV** [comment]
Please also check my last comment in #87

**Review by vinzvinci — CHANGES_REQUESTED** [review]
image

Just saw this dark gray on the developers page, can u fix it the same with the dark background?

**Comment by AbhinavMV** [comment]
> image
> 
> Just saw this dark gray on the developers page, can u fix it the same with the dark background?

That is extra spacing between features and team section.
it also there in light mode. 
So removing it will affect both modes.i hope that is ok

**Comment by vinzvinci** [comment]
> > image
> > Just saw this dark gray on the developers page, can u fix it the same with the dark background?
> 
> That is extra spacing between features and team section. it also there in light mode. So removing it will affect both modes.i hope that is ok

I see, let it be.

**Review by Panquesito7 — DISMISSED** [review]

**Comment by vinzvinci** [comment]
Please see the comments above

**Review by gptkrsh — CHANGES_REQUESTED** [review]
Can you update it with the colors like commented in the issue?

**Comment by AbhinavMV** [comment]
Will the above issue 
Found one more issue (maybe)
In light mode: **navbar has a shadow** 
image

In dark mode: is it needed here
image

**Comment by AbhinavMV** [comment]
Trying out the theme in docs right.
will update soon.

**Review by gptkrsh — CHANGES_REQUESTED** [review]
No shadow in dark mode

**Comment by AbhinavMV** [comment]
have changed the theme color 
if this does not look good let me know some color combo's(matching docs) or i could just undo the last commit

**Review by vinzvinci — DISMISSED** [review]
It looks good to me.

**Review by vinzvinci — APPROVED** [review]

**Review by gptkrsh — APPROVED** [review]

**Comment by vinzvinci** [comment]
Merged!

Please keep in touch with us, we will add new pages.

**Review by Panquesito7 — COMMENTED** [review]
LGTM! 🚀

**Pull request merged**
