### PR TITLE
feat: added stepbystep features & added some profile pic. to teams

### LINKED ISSUE #111: [FEATURE] Step by Step Onboarding section
### Detailed description

Step by Step Onboarding 

Step 1 
In order for you to register (or tokenize) your Open Source Project to Dev Protocol, you need to go through a registration procedure for Stakes.social. You’ll need a wallet to register, so you must have one beforehand. You can use any wallet provided there like MetaMask to log in on Stakes.social. 

Step 2 
Click the “Sign in” button located at the right side of the navigation bar to connect your wallet to Stakes.social and it will automatically login if you successfully connect your wallet to the Stakes.social. 

Step 3
Click the "Create" in navigation bar and answer the provided form. After you submit your application form, we kindly ask you to wait for about a week for the screening process. We’ll let you know the result via email, so please change the filtering setup for your mail box to receive an email from “@devprotocol.xyz”. 

Step 4 
If you successfully pass the screening, access the URL written in the approval email. We will send you another step-by-step method to completely onboard to the Stakes.social. You’ll need a gas fee for your registration. It fluctuates depending on the congestion condition, however, it would be around 0.0436ETH. Since the gas costs are constantly changing, it is safer to separate about 0.0875 ETH for the onboarding process.(edited)

### Context

This is the last section that needs to add for creators page

### Possible implementation

Feature: https://tailwindui.com/components/application-ui/lists/feeds

### Additional information

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### LINKED ISSUE #112: [FEATURE] Step by Step Staking section
### Detailed description

Step by Step Staking 

Step 1 
Staking is the act of actively setting aside your DEV tokens in your Wallet to deposit them in your favorite Creator pool on stakes.social. To buy DEV Token, you need an ETH on your wallet to convert it to $DEV. 

Step 2 
After you buy DEV Token, add the DEV token address in your wallet. You need to find a project that you like on Stakes.social. If you find a project interesting, you can click on the banner, the project page will show up, there you can find the description and some useful things like Github, Twitter pages, YouTube channel, Website, etc. This could help you decide to stake your $DEV. On the blue box, you can type a specific amount of DEV you want to stake on that project, or you can just click on DEV, and the total amount of DEV in your wallet will automatically show on that box.

Step 3 
After that, you can click on the blue Stake button and a transaction approval message will pop up in your wallet, you can check out the amount of gas required to Stake, by clicking approve, your DEV will be deposited on the contract and it will be staked. Once staked refresh the page and your DEV will show on the ‘Your Staking Amount’ box. You will instantly start receiving Rewards and so will the Creator that you chose, those can also be seen on the dashboard.

Step 4 
If you still can’t decide, my tip is, visit the official Discord or Telegram channel and ask the community. Always try to stake and reward active developers that promote DEV, this will be good for everyone on the long run. 

### Context

This is the last section that needs to add in Patrons section

### Possible implementation

Feature: https://tailwindui.com/components/application-ui/lists/feeds

### Additional information

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by vinzvinci**
#### Description of the change

I coded the remaining features and add team pictures

#### Checklist

- [x] Added description of the change
- [x] I've read the [contributing guidelines](https://github.com/web3community/devprotocol.xyz/blob/main/CONTRIBUTING.md)
- [x] Search previous suggestions before making a new PR, as yours may be a duplicate.
- [x] I acknowledge that all my contributions will be made under the project's license.

Notes (**optional**): 

<a href="https://gitpod.io/#https://github.com/web3community/devprotocol.xyz/pull/117"></a>

### CODE REVIEW

**Review by KukretiShubham — APPROVED** [review]
LGTM 🚀 
Pfp of `Andrew Giunta` and `Kent Kuroiwa` missing

**Comment by vinzvinci** [comment]
Yeah @KukretiShubham, I'm trying to contact them.

**Review by gptkrsh — APPROVED** [review]

**Review by mkubdev — COMMENTED** [review]
LGTM 👓

**Review by Panquesito7 — COMMENTED** [review]
Made a new PR to improve some of the texts. 🙂

**Pull request merged**
