### PR TITLE
fix stats page and update chart data

### LINKED ISSUE #223: [BUG] stats page doesn't display chart
### Problem subject

chart doesn't work on [stats page](https://devprotocol-bjfzuo6g8-devprtcl.vercel.app/stats). image is below.
image

### Description

In order to render a chart using d3.js, client rendering is specified for the chart component. like this `<Chart client:load />.`. But Astro's client rendering is not supported from ver 1.0 and chart is not display.
Error message is below
```
A PostCSS plugin did not pass the `from` option to `postcss.parse`. This may cause imported assets to be incorrectly transformed. If you've recently added a PostCSS plugin that raised this warning, please contact the package author to fix the issue.
You are attempting to render <Chart client:load />, but Chart is an Astro component. Astro components do not render in the client and should not have a hydration directive. Please use a framework component for client rendering.
```

### Expected behavior/contents

correct image is [here](https://user-images.githubusercontent.com/33506754/174722271-e63cbf64-ae8f-48dc-b31f-734693017810.png)

### Actual behavior/contents

doesn't show chart

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by osaguild**
#### Description of the change
This is a PR that includes bug fixes to the stats page for issue #223 and updated chart data.

#### Screenshots
image

#### Checklist

**I agree to the following :-**

- [x] Added description of the change
- [x] I've read the [contributing guidelines](https://github.com/dev-protocol/devprotocol.xyz/blob/main/CONTRIBUTING.md)
- [x] Search previous suggestions before making a new PR, as yours may be a duplicate.
- [x] I acknowledge that all my contributions will be made under the project's license.

Notes (**optional**):

### CODE REVIEW

**Review by vinzvinci — APPROVED** [review]
LGTM 👍 So it changed to vue now

**Review by gptkrsh — APPROVED** [review]
Looks cool! Thank you

**Comment by gptkrsh** [comment]
Fixes #223

**Review by vinzvinci — APPROVED** [review]
Need to merge this @aggre

**Review by aggre — APPROVED** [review]
LGTM!

**Pull request merged**
