### PR TITLE
[feat]: add WOM Web Recorder section

### PR DESCRIPTION
**Pull request by mkubdev**
#### Description of the change

* Added WOM Web Recorder scripts
* Added WOM Component to the homepage
* Basic styling

EDIT: Make it draft for fixing it. @krishguptadev Do you know how to deal with scripts with Astro? The player wont display because it seems to not read window.bullz object from component.

EDIT2: 
* Try with vue renderer --> CORS error when calling the script.
* Try with react renderer --> CORS Error + unkown error message.
* Try with .astro --> CORS error when calling the script.

#### Screenshots
* Astro wont deal with window object :
Capture d’écran 2021-12-18 180402

* When i manually inject the script inside the DevTool :
Capture d’écran 2021-12-18 185352

* Nextjs component on new next-create-app project :
Capture d’écran 2021-12-18 202251

#### Code

* WebRecorder component :
```js
import React, {useState, useEffect} from 'react';

const WebRecorder = () => {
    const webRecorderConfig = {
        organizationPublicld: "DEV PROTOCOL_619bbef3237f2c2d1f26ce9d",
        facilitatorld: "DEV PROTOCOL_619bbef3237f2c2d1f26ce9d",
        publisher: "Dev Protocol",
        selector: "#plugin-selector-D001",
        background: "https://stackroom.devprotocol.xyz/integration/wom/background.png",
        logo: "https://stackroom.devprotocol.xyz/brand/dev-protocol__avatar-brandmark--white--w_980.png",
        color: "white",
        backgroundColor: "black",
        remoteProduct: {
          name: "Dev Tokens",
          brand: "Dev Protocol",
          publicld: "D001",
          url: "https://devprotocol.xyz/",
          imageUrl: "https://stackroom.devprotocol.xyz/integration/wom/background.png",
        },
        isDev: false,
    }
  
    useEffect(() => {
            window.bullz.init(webRecorderConfig);      
    }, []);
  
    return (
      <div className="max-w-md mx-auto overflow-hidden md:max-w-6xl m-7">
        <div className="md:flex">
          <div className="p-8 mx-auto self-center md:text-left text-center">
            <span className="font-black font-display xl:text-3xl lg:text-2xl md:text-2xl text-5xl my-2">Earn WOM to recommend Dev Protocol on the BULLZ dapp!</span>
            <p className="mt-2 text-gray-500">Recommend Dev Protocol to your fans and community using the BULLZ dapp. You can use the web recorder to create video recommendations and earn WOM tokens for it!</p>
          </div>
          <div className="md:flex-shrink-0 flex sm:content-center">
            <div id="plugin-selector-D001" className="bg-gray-700 m-5 shadow-xl" style={{width: 285 + 'px', height: 600 + 'px'}} />
          </div>
        </div>
      </div>
    );
  };

  
export default WebRecorder;
```

#### Checklist

**I agree to the following :-**

* [x]   Added description of the change

* [x]   I've read the [contributing guidelines](https://github.com/web3community/devprotocol.xyz/blob/main/CONTRIBUTING.md)
* [x]   Search previous suggestions before making a new PR, as yours may be a duplicate.
* [x]   I acknowledge that all my contributions will be made under the project's license.

Notes (**optional**): 

* **Credentials `organizationPublicld` and `facilitatorld` of bullz-init script should be in a .env file !**

<a href="https://gitpod.io/#https://github.com/web3community/devprotocol.xyz/pull/200"></a>

### CODE REVIEW

**Review by vinzvinci — APPROVED** [review]
Wow, thank you master :p LGTM 👍

**Review by shuklaritvik06 — APPROVED** [review]

**Comment by vinzvinci** [comment]
If you're confused why it's only gray background on the right. Video will be provided by WOM soon :D

**Comment by shuklaritvik06** [comment]
> If you're confused why it's only gray background on the right. Video will be provided by WOM soon :D

Hehe yes I was thinking this 😅

**Comment by vinzvinci** [comment]
Don't merge. Make it draft @mkubdev

**Comment by vinzvinci** [comment]
Hmm I'm wrong there @shuklaritvik06, the main problem is window object... that's why it's not showing.

**Comment by shuklaritvik06** [comment]
> Hmm I'm wrong there @shuklaritvik06, the main problem is window object... that's why it's not showing.

Oh okay okay thanks :)

**Comment by mkubdev** [comment]
Hey there. Some update :
 *I think this framework isn't a viable solution to maintain the website..*
> There isn't any good ressources on Google. Stackoverflow can't help much. Error engine is broken.

It took me **30 secondes** on nextjs to implement the viewer :

```js
import React, {useState, useEffect} from 'react';

const WebRecorder = () => {
    const webRecorderConfig = {
        organizationPublicld: "DEV PROTOCOL_619bbef3237f2c2d1f26ce9d",
        facilitatorld: "DEV PROTOCOL_619bbef3237f2c2d1f26ce9d",
        publisher: "Dev Protocol",
        selector: "#plugin-selector-D001",
        background: "https://stackroom.devprotocol.xyz/integration/wom/background.png",
        logo: "https://stackroom.devprotocol.xyz/brand/dev-protocol__avatar-brandmark--white--w_980.png",
        color: "white",
        backgroundColor: "black",
        remoteProduct: {
          name: "Dev Tokens",
          brand: "Dev Protocol",
          publicld: "D001",
          url: "https://devprotocol.xyz/",
          imageUrl: "https://stackroom.devprotocol.xyz/integration/wom/background.png",
        },
        isDev: false,
    }
  
    useEffect(() => {
            window.bullz.init(webRecorderConfig);      
    }, []);
  
    return (
      <div className="max-w-md mx-auto overflow-hidden md:max-w-6xl m-7">
        <div className="md:flex">
          <div className="p-8 mx-auto self-center md:text-left text-center">
            <span className="font-black font-display xl:text-3xl lg:text-2xl md:text-2xl text-5xl my-2">Earn WOM to recommend Dev Protocol on the BULLZ dapp!</span>
            <p className="mt-2 text-gray-500">Recommend Dev Protocol to your fans and community using the BULLZ dapp. You can use the web recorder to create video recommendations and earn WOM tokens for it!</p>
          </div>
          <div className="md:flex-shrink-0 flex sm:content-center">
            <div id="plugin-selector-D001" className="bg-gray-700 m-5 shadow-xl" style={{width: 285 + 'px', height: 600 + 'px'}} />
          </div>
        </div>
      </div>
    );
  };

  
export default WebRecorder
```
And it's working as expected :

Capture d’écran 2021-12-18 202251

When i'm trying to add the same component to Astro, and using the Astro's react renderer, it give me this error :

Capture d’écran 2021-12-18 203005

* 404 : throw 404 not found but displaying the component

Unfortunatly, i can't help anymore !

**Comment by Simperfy** [comment]
Try renaming the `"bullz-init"` to `"bullz-recorder-init"` *(example above)* it worked for me.

**Comment by mkubdev** [comment]
🤒 Astro got me. Well done @Simperfy 👍🏻

**Pull request closed without merging**
