### PR TITLE
chore: use prettier

### LINKED ISSUE #90: [FEATURE] Use the prettier plugin
### Detailed description

Aggre asked this before to add **Prettier** plugin to automatically format the code

### Context

CC @krishguptadev 

### Possible implementation

https://github.com/snowpackjs/prettier-plugin-astro

### Additional information

image

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by gptkrsh**
Fixes #90 and updates Tailwindcss to fix dependency compatibility errors

### CODE REVIEW

**Review by Panquesito7 — DISMISSED** [review]
Looks good. Thanks! 🚀

Marked as `invalid` as this is a very easy fix
and I don't think it should count for Hacktoberfest.

**Comment by gptkrsh** [comment]
The greetings action is failing because of some error in the action - so I have added reviewpad which also adds many more features

**Comment by Panquesito7** [comment]
> The greetings action is failing because of some error in the action - so I have added reviewpad which also adds many more features

I think you should add ReviewPad in a separate PR.

**Comment by gptkrsh** [comment]
Removed Reviewpad - @Panquesito7

**Comment by gptkrsh** [comment]
There are too many conflicts, I think I'll just make a new pr

**Pull request closed without merging**
